### ISSUE TITLE
Не возможно использовать webhook chanel для алетов

### ISSUE THREAD

**Issue by wather777** [balerter/balerter#68]
Попытался использовать webhook chanel для передачи алертов в свой кастомный апи для телеграмм ботов.
`curl --header 'Content-Type: application/json' --request 'POST' --data '{"chat_id":"-11111111","text":"Тестовая отправка сообщения"}' http://proxy-api-url:8080/sendMessage`
но в https://balerter.com/0.9.1/configuration/channels.html#type-webhook 
Я сделал пытался сделать по аналогии с curl
````
channels:
  webhook:
    - name: wh1
      settings:
        url: http://proxy-api-url:8080/sendMessage
        method: POST
        payload:
          queryParams:
            chat_id: "-11111111"
            text: Алерт <----- Нельзя менять из скрипта
          body: body content <----- Нельзя менять из скрипта
        timeout: 5000
        headers:
            Content-Type: application/json
      ignore: false
````

нельзя менять текст параметра text....
